[project]
name = "sample1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyxel>=2.2.10",
]

[dependency-groups]
dev = [
    "ruff>=0.9.1",
]
